packages:
  - windows-app

overrides:
  "@electron/get": 3.1.0
  argparse: 1.0.10
  axios: 0.33.0
  nanoid: 3.3.18
  postcss: 8.5.23
  protobufjs: 7.6.5
  sharp: 0.35.0
  uuid: 11.1.1

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: false
  sharp: true
  tos-crc64-js: false
  workerd: true

minimumReleaseAgeExclude:
  - mammoth@1.12.1
