packages:
  - windows-app

overrides:
  "@electron/get": 3.1.0

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - mammoth@1.12.1
