export interface PresetSkill {
  id: string;
  agentId: "director" | "writer" | "storyboard" | "video" | "voice" | "editor";
  title: string;
  content: string;
  tags: string[];
  source: string;
  sourceUrl: string;
}

export const PRESET_SKILLS: PresetSkill[] = [
  {
    id: "director-creative-brief",
    agentId: "director",
    title: "导演任务拆解与创作总纲",
    content: "收到需求后先输出创作总纲，再分派任务。总纲必须明确：目标观众、平台与画幅、总时长、核心情绪、主角欲望、主要冲突、视觉风格、节奏曲线、不可违反的限制。信息不足时只询问会改变成片方向的问题；其余作出明确假设并标注。每个部门的交付都要能追溯到总纲，发现偏离时先指出偏离点，再给可执行修正。",
    tags: ["导演", "创作总纲", "任务拆解", "质量控制"],
    source: "漫镜预设 · ViMax 方法启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "director-visual-bible",
    agentId: "director",
    title: "视觉圣经与跨镜头一致性",
    content: "开工前建立视觉圣经：人物固定特征、服装与道具、场景空间关系、时代与天气、主色与禁用色、光线方向、镜头质感和参考图。审查每个镜头时逐项核对人物身份、左右位置、服装、道具持有、时间、光源、色调和画幅。变化必须来自剧情，不允许模型随机变化。重要参考图应设为工作锚点，并在后续提示词中使用同一套稳定描述。",
    tags: ["视觉一致性", "角色一致性", "参考图", "工作锚点"],
    source: "漫镜预设 · ViMax 方法启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "director-review-gate",
    agentId: "director",
    title: "分阶段 PASS/REVISE 质量闸门",
    content: "剧本、分镜、角色图、视频片段、配音和成片都必须经过独立审查。输出只能是 PASS 或 REVISE，并列出具体问题、影响和最小修复动作。重点检查：叙事是否清楚、角色是否一致、镜头信息是否完整、动作是否物理合理、轴线和视线是否连续、音画是否同步、平台时长是否满足。连续两次修订仍失败时缩小问题范围；三次失败后停止消耗生成额度并请求用户决策。",
    tags: ["审核", "PASS", "修订循环", "成本控制"],
    source: "漫镜原创预设 · 开源多 Agent 工作流综合",
    sourceUrl: "https://github.com/seme-org/open-director",
  },
  {
    id: "director-emotion-rhythm",
    agentId: "director",
    title: "情绪节奏与镜头调度",
    content: "先为每场戏写出情绪起点、转折点和落点，再决定景别、机位和运动。情绪建立用环境与关系镜头，冲突升级逐步缩短镜头或靠近主体，关键反应留出停顿，高潮后安排释放空间。运镜必须服务信息和情绪，禁止为了炫技无目的移动。对白场优先保证表演、视线和反应镜头，动作场优先保证方向、因果和空间可读性。",
    tags: ["情绪", "节奏", "运镜", "表演"],
    source: "漫镜原创预设 · 影视导演通用方法",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "writer-scene-engine",
    agentId: "writer",
    title: "场景目标、冲突与转折",
    content: "每场戏必须回答：谁想要什么、阻力是什么、采取了什么行动、局势如何变化、为什么必须进入下一场。场景开头尽快建立目标，中段通过行动和反应升级冲突，结尾产生新信息、新决定或不可逆后果。删除只重复信息而不改变关系或局势的场景。输出剧本时标明场次、内外景、地点、时间、人物、动作、对白和情绪潜台词。",
    tags: ["剧本", "场景", "冲突", "转折"],
    source: "漫镜原创预设 · ViMax 结构化脚本启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "writer-character-voice",
    agentId: "writer",
    title: "人物弧光与差异化对白",
    content: "为主要人物建立：外在目标、内在缺口、恐惧、秘密、底线、关系变化和说话习惯。对白先表达行动目的，再通过潜台词体现真实情绪；不同人物必须在词汇、句长、语气、回避方式和幽默感上可区分。避免让人物直接解释观众已经看到的信息。每场戏后检查人物选择是否符合当前认知，并记录新获得的信息，保证后续连续性。",
    tags: ["人物", "对白", "潜台词", "人物弧光"],
    source: "漫镜原创预设 · 开源故事生成工作流综合",
    sourceUrl: "https://github.com/seme-org/open-director",
  },
  {
    id: "writer-adaptation-compression",
    agentId: "writer",
    title: "长文本改编与短剧压缩",
    content: "改编时先提取主线承诺、核心人物关系、必要因果和观众最期待的兑现点。按目标时长分配信息预算，合并功能重复的人物和场景，用可视化行动替代旁白解释。短视频前3秒必须建立异常、欲望或问题；每15至30秒提供一次信息变化；结尾完成情绪兑现或留下明确悬念。不得为了压缩破坏关键因果。",
    tags: ["改编", "短剧", "信息密度", "钩子"],
    source: "漫镜原创预设 · Pexo 多场景内容方法启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "writer-continuity-check",
    agentId: "writer",
    title: "剧本连续性自检",
    content: "交付前建立连续性表并核对：人物所在地点、时间推进、已知信息、伤势与服装、持有道具、关系状态、未完成承诺和伏笔。检查每个结果是否有前置原因，每个重要铺垫是否有回收，每个角色是否在不知情时说出不该知道的信息。发现矛盾时优先修复最早的因果节点，不用新增解释性对白掩盖问题。",
    tags: ["连续性", "因果", "伏笔", "自检"],
    source: "漫镜原创预设 · ViMax 长叙事一致性启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "storyboard-beat-to-shot",
    agentId: "storyboard",
    title: "从剧情 Beat 拆成可生成镜头",
    content: "先把场景拆成信息或情绪 Beat，再为每个 Beat 选择最少但足够的镜头。每个镜头只承担一个主要叙事任务，并写清：镜头编号、时长、景别、机位角度、构图、主体位置、动作起点与终点、镜头运动、台词或声音、转场理由。若一个镜头包含多个难以同时生成的动作，应继续拆分，不把复杂事件塞进单条提示词。",
    tags: ["分镜", "Beat", "镜头拆解", "镜头表"],
    source: "漫镜原创预设 · Pexo/ViMax 多镜头方法启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "storyboard-screen-direction",
    agentId: "storyboard",
    title: "轴线、视线与屏幕方向连续性",
    content: "建立场景平面关系和动作轴线，记录人物在画面左/右、面对方向、视线目标和运动方向。正反打保持视线匹配；跨轴必须用中性机位、运动镜头或明确的过渡镜头交代。人物离开画面的方向应与下一镜进入方向形成连续。剪接前后同时检查主体位置、动作相位、景别变化和视线，不允许无意跳切。",
    tags: ["轴线", "视线", "方向", "连续性"],
    source: "漫镜原创预设 · 影视分镜通用方法",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "storyboard-shot-spec",
    agentId: "storyboard",
    title: "AI 分镜提示词规格",
    content: "每条画面提示词按固定顺序编写：角色稳定描述、当前服装与道具、具体动作、表情与视线、场景和时间、主体位置与构图、景别和焦段感、机位角度、光线方向、色彩与风格、画幅、禁止项。不要只写抽象情绪。相邻镜头复用完全相同的角色与场景锚点，只改变本镜头需要变化的动作、机位和构图。",
    tags: ["提示词", "构图", "角色一致性", "分镜图"],
    source: "漫镜原创预设 · ViMax 参考管理启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "storyboard-first-last-frame",
    agentId: "storyboard",
    title: "首尾帧与镜头衔接设计",
    content: "为视频镜头明确首帧和尾帧状态：主体位置、姿态、视线、道具、背景关系和运动趋势。尾帧应为下一镜提供可接的方向、动作或构图，不要让人物在镜头末尾随机换位。需要连续运动时，下一镜首帧继承上一镜尾帧；需要跳时空时，明确使用声音桥、相似构图、动作匹配或过渡镜头。",
    tags: ["首帧", "尾帧", "衔接", "动作匹配"],
    source: "漫镜原创预设 · ViMax 首帧与连续性启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "video-model-routing",
    agentId: "video",
    title: "按镜头需求选择视频模型",
    content: "选择模型前识别镜头类型：文生视频、图生视频、首尾帧、人物表演、快速运动、产品展示或风格化镜头。优先使用用户已配置且验证可用的模型，不虚构模型参数。提交前检查模型支持的时长、画幅、分辨率、参考图数量和必填字段。模型失败时保留任务与素材，区分鉴权、参数、队列、生成和下载错误，再决定重试、降级或换模型。",
    tags: ["视频模型", "模型路由", "失败处理", "参数检查"],
    source: "漫镜原创预设 · Pexo 自动路由启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "video-shot-duration",
    agentId: "video",
    title: "15秒以内逐镜生成与长视频组装",
    content: "任何超过模型单次上限的视频都必须先拆成独立镜头，默认单镜控制在3至10秒，绝不把长视频当作一次生成任务。逐镜生成时保存镜头编号、首尾帧、提示词、模型、时长、任务ID和结果文件。上一镜通过后再确认下一镜的衔接条件；失败只重跑该镜头。全部镜头完成后交给剪辑 Agent 按分镜顺序组装。",
    tags: ["15秒", "逐镜生成", "长视频", "断点续作"],
    source: "漫镜原创预设 · ViMax/Pexo 多镜头启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "video-motion-prompt",
    agentId: "video",
    title: "可控运动提示词",
    content: "运动提示词只描述时间内发生的变化，结构为：主体初始状态、主要动作、动作速度和幅度、镜头运动、环境动态、结束状态、稳定性限制。动作必须符合人物关节、重力和场景空间。避免同时要求多个冲突运镜或过多动作。人物镜头补充面部稳定、手部自然、服装不变；图生视频时不重复改写参考图中已经确定的外观。",
    tags: ["运动提示词", "物理合理", "图生视频", "稳定性"],
    source: "漫镜原创预设 · ViMax 镜头设计启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "video-result-qc",
    agentId: "video",
    title: "视频生成结果验收与最小重试",
    content: "生成后按镜头逐项验收：主体身份、脸和手、服装道具、动作完成度、背景稳定、镜头运动、首尾帧、时长、分辨率和可播放性。只记录可观察问题，不用模糊评价。若失败，先锁定未出错部分，再只修改导致问题的一个或两个变量；连续失败应缩短动作、降低幅度或拆镜。通过的片段立即进入资产库并关联项目和镜头编号。",
    tags: ["视频验收", "重试", "资产库", "质量控制"],
    source: "漫镜原创预设 · ViMax 渲染检查点启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "voice-character-profile",
    agentId: "voice",
    title: "角色声线档案与选角",
    content: "为每个角色建立声线档案：年龄感、音高、音色、语速、力度、口音、呼吸感、情绪范围、参考音频和禁止特征。同一角色跨场次优先复用相同音色与参数。选角时先匹配人物身份和表演需求，再考虑音色好听与否。声音克隆只使用用户有权使用的样本，并记录授权来源。",
    tags: ["声线", "选角", "声音一致性", "授权"],
    source: "漫镜原创预设 · SmartSub/ZastTranslate 启发（MIT）",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },
  {
    id: "voice-performance-markup",
    agentId: "voice",
    title: "对白表演标注",
    content: "合成前把台词按意群切分，并标注说话对象、行动目的、潜台词、情绪强度、重音、停顿、速度变化和句尾走向。情绪不等于全句同一种强度，重要变化应落在关键词和停顿上。旁白优先清晰与节奏，对话优先人物关系和即时反应。避免用标点堆砌代替真实表演指令。",
    tags: ["对白", "表演", "重音", "停顿"],
    source: "漫镜原创预设 · 配音工作流综合",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },
  {
    id: "voice-timing-fit",
    agentId: "voice",
    title: "逐句时长匹配与单句重合成",
    content: "按字幕时间段逐句生成并测量真实音频时长。优先通过自然停顿、语速小幅调整和借用静音间隙匹配时间；超限时先精简不影响意思的文字，再考虑变速。不得直接截断台词。问题句单独试听、修改和重合成，不重跑整段。记录每句开始、结束、实际时长、音色和修改原因。",
    tags: ["时长匹配", "逐句", "重合成", "字幕"],
    source: "漫镜预设 · SmartSub/ZastTranslate 方法启发（MIT）",
    sourceUrl: "https://github.com/zast57/ZastTranslate",
  },
  {
    id: "voice-audio-qc",
    agentId: "voice",
    title: "配音质量检查与音轨交付",
    content: "交付前逐句检查错字、漏字、多音字、人名读音、爆音、底噪、音量突变、语速、情绪和时间轴。对白、旁白、环境声和音乐分轨保存。混音时对白优先，音乐遇对白自动压低但不完全消失；必要时保留原环境声。输出音频时附带字幕、角色音色映射和需要人工复核的异常清单。",
    tags: ["配音验收", "混音", "音轨", "异常清单"],
    source: "漫镜预设 · SmartSub 方法启发（MIT）",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },

  {
    id: "editor-assembly",
    agentId: "editor",
    title: "按叙事功能组装镜头",
    content: "先按分镜和场次组装粗剪，不先堆转场和特效。每次剪切必须回答：观众此刻需要看见什么、为什么现在切、切后获得什么新信息。优先保证因果、空间、动作和情绪连续，再调整节奏。反应镜头应放在引发反应的动作之后；信息未读清前不要过早切走；重复表达同一信息的镜头应精简。",
    tags: ["剪辑", "粗剪", "叙事", "节奏"],
    source: "漫镜原创预设 · Pexo 多镜头组装启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "editor-continuity",
    agentId: "editor",
    title: "剪辑连续性与转场选择",
    content: "逐剪检查动作相位、屏幕方向、视线、主体位置、亮度色温、环境声和说话口型。优先使用硬切、动作匹配、视线匹配和声音桥；只有时空、情绪或段落确实变化时才使用明显转场。AI 片段首尾不稳定时先裁掉异常帧，再判断能否通过插入反应、环境或特写镜头修复，不用花哨转场掩盖连续性错误。",
    tags: ["连续性", "转场", "动作匹配", "声音桥"],
    source: "漫镜原创预设 · ViMax 连续性启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "editor-subtitle",
    agentId: "editor",
    title: "字幕断句、校对与可读性",
    content: "字幕按语义和呼吸断句，不把连接词、姓名或固定词组拆开。逐句核对画面、音频和文字，修正错字、多音字、标点和时间轴。控制每行长度和屏幕停留时间，重要信息避免与画面关键文字重叠。修改字幕后同步检查配音脚本；问题行支持单独恢复、重做和重新合成。",
    tags: ["字幕", "断句", "校对", "可读性"],
    source: "漫镜预设 · SmartSub 方法启发（MIT）",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },
  {
    id: "editor-mix-export",
    agentId: "editor",
    title: "音频混合与平台导出验收",
    content: "混音顺序为对白清晰、环境连续、音乐服务情绪、音效强调关键动作。对白期间对音乐做平滑 ducking，避免突然抽空；镜头切换处保留连续环境底。导出前检查总时长、画幅、分辨率、帧率、音画同步、黑帧、静音、字幕安全区和文件可播放性。根据平台分别生成9:16、16:9或1:1版本，不用简单裁切破坏主体构图。",
    tags: ["混音", "导出", "画幅", "平台适配"],
    source: "漫镜预设 · Pexo/SmartSub 方法启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
];
