import { IMPORTED_DEFAULT_SKILLS } from "./imported-default-skills";

export interface PresetSkill {
  id: string;
  agentId: "producer" | "director" | "writer" | "character" | "scene" | "storyboard" | "prompt" | "image" | "video" | "voice" | "editor";
  title: string;
  content: string;
  tags: string[];
  source: string;
  sourceUrl?: string;
}

export const PRESET_SKILLS: PresetSkill[] = [
  {
    id: "director-seedance-reference-plan",
    agentId: "director",
    title: "Seedance 多模态素材分工与镜头可行性审查",
    content: "开拍前把参考素材按职责分工：人物角色卡只负责身份、脸型、体型与当集造型；Canonical 场景图负责空间、光线与环境风格；道具图负责形状、材质和归属；已批准视频负责动作节奏与连续状态；音频负责人物音色与语气。每镜优先控制在1–2张人物身份图、1张场景图、必要道具、至多1段动作/节奏视频和1段音色参考的精简集合，先满足叙事必要性再增加素材。审查时必须确认谁、在哪里、做一个什么主动作、镜头如何运动、结束在哪里；动作过多、多人关系含糊、素材职责冲突或参考数量过载时，先拆镜或删减，不把问题留给视频模型猜。",
    tags: ["Seedance 2.0", "多模态参考", "素材分工", "镜头可行性", "默认启用"],
    source: "用户提供 · Seedance 2.0 影视场景提示词指南（工程化摘要）",
  },
  {
    id: "storyboard-seedance-action-budget",
    agentId: "storyboard",
    title: "Seedance 单镜动作预算与时间分段",
    content: "一个生成镜头只承担一个主动作或一个清晰情绪变化。先写0秒初始状态，再把过程拆成最多三个可见阶段，最后写可审核的结束状态；5秒镜头只安排一个简单动作，10–15秒也只允许一个主动作配少量连续小动作。若剧情包含靠近、交接、转身、奔跑、跌倒、反应等多个因果节点，应拆成多个分镜，通过景别变化、反应镜头或动作匹配剪辑组接。每镜明确人物左右/前后位置、朝向、手脚、重心、道具归属、视线和镜头运动，避免抽象情绪代替可见行为。",
    tags: ["Seedance 2.0", "动作预算", "时间轴", "分镜拆解", "默认启用"],
    source: "用户提供 · seedance2.0 提示词 Skill 与场景指南（工程化摘要）",
  },
  {
    id: "prompt-seedance-engineered-instruction",
    agentId: "prompt",
    title: "Seedance 工程化提示词：正向锁定、显式映射与三段动作",
    content: "最终提示词按固定顺序编译：①一句话场景与镜头任务；②逐项写明每个 @Image/@Video/@Audio 的名称和唯一职责，不依赖 Asset ID 或上传顺序让模型猜图号；③人物初始状态（位置、朝向、双手、双脚、重心、视线、道具）；④一个主动作及最多三步时间过程；⑤镜头轨迹、速度和稳定方式；⑥画质、风格、光线与结束状态。Seedance 可能把负面描述中的视觉词也激活，故优先使用“始终站立、双脚位于踏步区、身体朝向控制面板”一类正向可见约束，少写含目标错误动作的大段禁止项；失败后先删除触发词、减少动作和参考冲突，不继续堆砌否定词。多人镜头必须用姓名和画面位置建立一一映射。不得提交 first_frame/last_frame 控制；上一镜真实尾帧只用于上游生成并选择不同机位的备选 @Image。",
    tags: ["Seedance 2.0", "提示词工程", "正向约束", "参考映射", "默认启用"],
    source: "用户提供 · seedance2.0 提示词 Skill 与场景指南（工程化摘要）",
  },
  {
    id: "image-original-character-face-design",
    agentId: "image",
    title: "原创角色脸谱设计：结构、比例与一个记忆点",
    content: "角色生图先从剧本身份、年龄、性格、阶层、距离感和戏剧功能推导脸部结构，不用“好看、精致、高级”代替设计。依次明确：脸型外轮廓、颧骨/下颌/下巴；中庭与下庭、眼距与眉眼距离、鼻梁和面中饱满度；一个主要五官记忆点加两个辅助特征；自然表情、眼神和嘴角；发型、妆面、服装领口、材质、配饰和服务骨相的光线。不同人物必须在头脸轮廓、三庭五眼、主记忆点、年龄感和气质上形成可见差异，避免网红同脸、锥子下巴、过高鼻梁、全五官同时抢戏、塑料磨皮和身份不符的妆造。原创角色不得以明星、网红、影视角色或真实人物相似脸为目标；参考图只分析结构、比例、妆造和气质。动画角色应用同样的结构与主次逻辑，但以目标动画媒介的材质和造型语言表达，不强行添加真人毛孔。",
    tags: ["生图", "原创角色", "脸型结构", "三庭五眼", "反同脸", "默认启用"],
    source: "用户提供 · 原创AI角色捏脸Skill.md（岗位摘要）",
  },
  {
    id: "video-seedance-reference-and-repair",
    agentId: "video",
    title: "Seedance 参考执行、局部修复与失败降复杂度",
    content: "提交前核对媒体参考与文字映射一致：每个人物、场景、道具、视频动作和音色都必须有明确职责，删除重复、互相冲突、不可访问或超过上限的素材。生成中保持一个主动作、一个主要镜头运动和稳定环境运动；人物位置、朝向、重心、道具归属与结束状态都应可在抽帧中检查。局部问题优先只重做当前镜头并锁住未修改的角色、场景、动作相位和光色；动作歧义或肢体失败时先改成正向身体状态、缩短动作链、降低运镜复杂度。不要用大量否定词激活错误视觉，不把未经用户确认的参考关系或九宫格图号交给模型自行推断。",
    tags: ["Seedance 2.0", "全能参考", "局部修复", "降复杂度", "默认启用"],
    source: "用户提供 · Seedance 2.0 影视场景提示词指南（工程化摘要）",
  },
  {
    id: "editor-seedance-continuation-choice",
    agentId: "editor",
    title: "连续动作、换机位与剪辑组接选择",
    content: "不要默认把长剧情硬续成一个镜头。先判断衔接目标：同一空间的核心动作必须一镜连续时，保持动作方向、速度和结束状态；复杂动作、对白、反应或需要明显换景别时，优先拆镜并用硬切、正反打、动作匹配或声音桥组接。上一镜真实尾帧仅作为生成不同角度/景别备选画面的来源，用户选定备选机位后再制作下一镜；原始尾帧不直接锁死下一镜构图。剪辑验收比较切点前后的人物身份、位置关系、动作相位、道具、光色与声音连续性，用镜头语言掩盖微小生成误差，而不是依赖无限续写。",
    tags: ["剪辑", "动作匹配", "换机位", "尾帧备选", "默认启用"],
    source: "用户提供 · Seedance 2.0 影视场景提示词指南（工程化摘要）",
  },
  {
    id: "director-ai-drama-production-bible",
    agentId: "director",
    title: "AI 漫剧项目制作圣经与开工检查",
    content: "开工前建立项目制作圣经：角色身份与当前造型、可复用表情和声音档案、场景空间布局、关键道具、时代天气、全局画风、主色、光线方向、动态强度、镜头速度、字幕和声音标准。先区分长期 Canonical 资产、当前集造型资产、镜头临时状态和声音资产；旁白、广告声、系统播报不得建立人物视觉资产。规则默认执行但不机械限制创作：镜头时长、景别跳切和位置变化可因剧情成立，变化必须有明确叙事原因和状态记录。",
    tags: ["漫剧SOP", "制作圣经", "资产规划", "开工检查"],
    source: "用户提供 · AI漫剧完整精细化生产SOP（经漫镜工程化修订）",
    sourceUrl: "https://github.com/Laity1m/manjing-desktop",
  },
  {
    id: "prompt-shot-match-and-screen-direction",
    agentId: "prompt",
    title: "镜头动作咬合、轴线与空间连续性",
    content: "编译视频提示词时读取上一镜文字 End State，并在方舟仍可访问时把上一镜已批准视频作为普通 @Video 全能参考。只有上一镜已生成且已审核通过的视频，才允许由本地视频解码器截取真实尾帧；先让生图岗位以该真实尾帧和 Canonical 资产生成至少三个不同景别/角度的备选机位，用户选择后，下一镜视频只引用选中的备选画面。原始尾帧不直接充当下一镜构图，绝不把 AI 备选图冒充真实尾帧，禁止提交 first_frame、last_frame 控制参数。每镜同时绑定当前任务 Canonical 人物、造型、场景、道具和可用音色。本镜开头约 0.5 秒用结构化提示词强约束上一镜姿态、视线、朝向、左右位置、景深层级、手持道具、门窗状态和光线，但不得宣称绝对锁定。结尾预留清晰可继承的动作姿态。对话场优先硬切和反应镜头，连续动作使用 match cut，换场才使用短淡入。统一同场镜头的呼吸幅度、发丝衣物动态、运镜速度和曝光色调。复杂连续长动作拆成短片段生成。",
    tags: ["漫剧SOP", "动作咬合", "180度轴线", "空间连续", "转场"],
    source: "用户提供 · AI漫剧完整精细化生产SOP（经漫镜工程化修订）",
    sourceUrl: "https://github.com/Laity1m/manjing-desktop",
  },
  {
    id: "editor-ai-drama-finishing-standard",
    agentId: "editor",
    title: "漫剧统一色彩、声音与交付标准",
    content: "合成前统一所有片段的分辨率、帧率和画幅；相邻镜头执行曝光、白平衡、对比度、饱和度和锐度匹配，避免明暗与色温跳变。角色对白使用固定声音档案并统一语速和响度，BGM 跨镜头连续播放，只在场次或情绪节点换段；字幕字体、字号、安全区和位置全片一致。转场以硬切为默认，动作衔接只加 0.1–0.2 秒必要柔化，场景切换才使用短淡入淡出。导出前检查黑帧、静帧、音画错位、爆音、字幕越界和时长。",
    tags: ["漫剧SOP", "色彩匹配", "响度", "字幕", "成片交付"],
    source: "用户提供 · AI漫剧完整精细化生产SOP（经漫镜工程化修订）",
    sourceUrl: "https://github.com/Laity1m/manjing-desktop",
  },
  {
    id: "prompt-canonical-asset-binding",
    agentId: "prompt",
    title: "Canonical 资产绑定与调用",
    content: "编译视频提示词前，必须先读取当前项目、剧集与镜头编号，再绑定已锁定的人物身份、当前造型、场景、关键道具、上一镜结束画面和可用声音资产。优先使用 Canonical 资产 ID，不得仅凭相似名称猜测资产。提示词中明确哪些内容必须保持、哪些内容允许变化；找不到必要资产时标记缺失，不得虚构已经绑定。",
    tags: ["Canonical", "资产调用", "人物一致性", "项目资产"],
    source: "漫镜内置 · 镜头总控 Agent",
    sourceUrl: "https://github.com/Laity1m/manjing-desktop",
  },
  {
    id: "prompt-state-propagation",
    agentId: "prompt",
    title: "Start State / End State 镜头状态传递",
    content: "每个镜头提示词必须读取上一镜 End State 作为本镜 Start State，核对人物位置、朝向、动作姿态、手持道具、门窗状态、服装、时间和光线。只有剧本明确发生变化时才能修改状态。提示词结尾写明本镜必须达到的 End State，为下一镜提供可继承状态。",
    tags: ["Start State", "End State", "连续性", "状态传递"],
    source: "漫镜内置 · 镜头总控 Agent",
    sourceUrl: "https://github.com/Laity1m/manjing-desktop",
  },
  {
    id: "prompt-seedance-camera-language",
    agentId: "prompt",
    title: "Seedance 2.0 运镜提示词编排",
    content: "根据导演意图选择且只选择必要运镜。推进用于加强主体和情绪，拉远用于揭示环境，横移用于跟随或展示空间，环绕用于突出主体关系，升降用于尺度变化，甩镜用于明确转场，跟拍用于连续行动。提示词按主体初始状态、动作过程、运镜方向与速度、环境动态、结束状态、稳定性限制的顺序编写；避免同时堆叠冲突运镜和过多动作。",
    tags: ["Seedance 2.0", "运镜", "提示词", "镜头语言"],
    source: "漫镜内置 · Seedance 运镜规范",
    sourceUrl: "https://github.com/Laity1m/manjing-desktop",
  },
  {
    id: "director-creative-brief",
    agentId: "director",
    title: "导演任务拆解与创作总纲",
    content: "收到需求后先输出创作总纲，再分派任务。总纲必须明确：目标观众、平台与画幅、总时长、核心情绪、主角欲望、主要冲突、视觉风格、节奏曲线、不可违反的限制。信息不足时只询问会改变成片方向的问题；其余作出明确假设并标注。每个部门的交付都要能追溯到总纲，发现偏离时先指出偏离点，再给可执行修正。",
    tags: ["导演", "创作总纲", "任务拆解", "质量控制"],
    source: "漫镜预设 · ViMax 方法启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "director-visual-bible",
    agentId: "director",
    title: "视觉圣经与跨镜头一致性",
    content: "开工前建立视觉圣经：人物固定特征、服装与道具、场景空间关系、时代与天气、主色与禁用色、光线方向、镜头质感和参考图。审查每个镜头时逐项核对人物身份、左右位置、服装、道具持有、时间、光源、色调和画幅。变化必须来自剧情，不允许模型随机变化。重要参考图应设为工作锚点，并在后续提示词中使用同一套稳定描述。",
    tags: ["视觉一致性", "角色一致性", "参考图", "工作锚点"],
    source: "漫镜预设 · ViMax 方法启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "director-review-gate",
    agentId: "director",
    title: "分阶段 PASS/REVISE 质量闸门",
    content: "剧本、分镜、角色图、视频片段、配音和成片都必须经过独立审查。输出只能是 PASS 或 REVISE，并列出具体问题、影响和最小修复动作。重点检查：叙事是否清楚、角色是否一致、镜头信息是否完整、动作是否物理合理、轴线和视线是否连续、音画是否同步、平台时长是否满足。连续两次修订仍失败时缩小问题范围；三次失败后停止消耗生成额度并请求用户决策。",
    tags: ["审核", "PASS", "修订循环", "成本控制"],
    source: "漫镜原创预设 · 开源多 Agent 工作流综合",
    sourceUrl: "https://github.com/seme-org/open-director",
  },
  {
    id: "director-emotion-rhythm",
    agentId: "director",
    title: "情绪节奏与镜头调度",
    content: "先为每场戏写出情绪起点、转折点和落点，再决定景别、机位和运动。情绪建立用环境与关系镜头，冲突升级逐步缩短镜头或靠近主体，关键反应留出停顿，高潮后安排释放空间。运镜必须服务信息和情绪，禁止为了炫技无目的移动。对白场优先保证表演、视线和反应镜头，动作场优先保证方向、因果和空间可读性。",
    tags: ["情绪", "节奏", "运镜", "表演"],
    source: "漫镜原创预设 · 影视导演通用方法",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "writer-scene-engine",
    agentId: "writer",
    title: "场景目标、冲突与转折",
    content: "每场戏必须回答：谁想要什么、阻力是什么、采取了什么行动、局势如何变化、为什么必须进入下一场。场景开头尽快建立目标，中段通过行动和反应升级冲突，结尾产生新信息、新决定或不可逆后果。删除只重复信息而不改变关系或局势的场景。输出剧本时标明场次、内外景、地点、时间、人物、动作、对白和情绪潜台词。",
    tags: ["剧本", "场景", "冲突", "转折"],
    source: "漫镜原创预设 · ViMax 结构化脚本启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "writer-character-voice",
    agentId: "writer",
    title: "人物弧光与差异化对白",
    content: "为主要人物建立：外在目标、内在缺口、恐惧、秘密、底线、关系变化和说话习惯。对白先表达行动目的，再通过潜台词体现真实情绪；不同人物必须在词汇、句长、语气、回避方式和幽默感上可区分。避免让人物直接解释观众已经看到的信息。每场戏后检查人物选择是否符合当前认知，并记录新获得的信息，保证后续连续性。",
    tags: ["人物", "对白", "潜台词", "人物弧光"],
    source: "漫镜原创预设 · 开源故事生成工作流综合",
    sourceUrl: "https://github.com/seme-org/open-director",
  },
  {
    id: "writer-adaptation-compression",
    agentId: "writer",
    title: "长文本改编与短剧压缩",
    content: "改编时先提取主线承诺、核心人物关系、必要因果和观众最期待的兑现点。按目标时长分配信息预算，合并功能重复的人物和场景，用可视化行动替代旁白解释。短视频前3秒必须建立异常、欲望或问题；每15至30秒提供一次信息变化；结尾完成情绪兑现或留下明确悬念。不得为了压缩破坏关键因果。",
    tags: ["改编", "短剧", "信息密度", "钩子"],
    source: "漫镜原创预设 · Pexo 多场景内容方法启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "writer-continuity-check",
    agentId: "writer",
    title: "剧本连续性自检",
    content: "交付前建立连续性表并核对：人物所在地点、时间推进、已知信息、伤势与服装、持有道具、关系状态、未完成承诺和伏笔。检查每个结果是否有前置原因，每个重要铺垫是否有回收，每个角色是否在不知情时说出不该知道的信息。发现矛盾时优先修复最早的因果节点，不用新增解释性对白掩盖问题。",
    tags: ["连续性", "因果", "伏笔", "自检"],
    source: "漫镜原创预设 · ViMax 长叙事一致性启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "storyboard-beat-to-shot",
    agentId: "storyboard",
    title: "从剧情 Beat 拆成可生成镜头",
    content: "先把场景拆成信息或情绪 Beat，再为每个 Beat 选择最少但足够的镜头。每个镜头只承担一个主要叙事任务，并写清：镜头编号、时长、景别、机位角度、构图、主体位置、动作起点与终点、镜头运动、台词或声音、转场理由。若一个镜头包含多个难以同时生成的动作，应继续拆分，不把复杂事件塞进单条提示词。",
    tags: ["分镜", "Beat", "镜头拆解", "镜头表"],
    source: "漫镜原创预设 · Pexo/ViMax 多镜头方法启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "storyboard-screen-direction",
    agentId: "storyboard",
    title: "轴线、视线与屏幕方向连续性",
    content: "建立场景平面关系和动作轴线，记录人物在画面左/右、面对方向、视线目标和运动方向。正反打保持视线匹配；跨轴必须用中性机位、运动镜头或明确的过渡镜头交代。人物离开画面的方向应与下一镜进入方向形成连续。剪接前后同时检查主体位置、动作相位、景别变化和视线，不允许无意跳切。",
    tags: ["轴线", "视线", "方向", "连续性"],
    source: "漫镜原创预设 · 影视分镜通用方法",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "storyboard-shot-spec",
    agentId: "storyboard",
    title: "AI 分镜提示词规格",
    content: "每条画面提示词按固定顺序编写：角色稳定描述、当前服装与道具、具体动作、表情与视线、场景和时间、主体位置与构图、景别和焦段感、机位角度、光线方向、色彩与风格、画幅、禁止项。不要只写抽象情绪。相邻镜头复用完全相同的角色与场景锚点，只改变本镜头需要变化的动作、机位和构图。",
    tags: ["提示词", "构图", "角色一致性", "分镜图"],
    source: "漫镜原创预设 · ViMax 参考管理启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "storyboard-first-last-frame",
    agentId: "storyboard",
    title: "全能参考与镜头衔接设计",
    content: "为每个视频镜头写明文字 Start State 与 End State：主体世界位置、屏幕左右、景深层级、姿态、视线、道具归属、背景关系和运动趋势。下一镜读取 End State 并重新投影到新机位；需要连续运动时用动作相位和上一镜已批准视频作为 @Video 全能参考。上一镜审核通过后，从其实际生成视频解码真实尾帧，再据此生成过肩、侧面、反打等不同景别/角度备选画面；用户必须选定一个备选机位后才可生成下一镜。真实尾帧与 AI 生成的备选图必须明确区分，原始尾帧不得直接锁死下一镜构图，任何图片都不得作为 first_frame、last_frame 控制。需要跳时空时使用声音桥、相似构图、动作匹配或过渡镜头。人物、造型、场景和道具图片只作为 @Image 全能参考。",
    tags: ["全能参考", "前序视频", "衔接", "动作匹配"],
    source: "漫镜原创预设 · 全能参考连续性工作流",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "image-aesthetic-art-direction",
    agentId: "image",
    title: "生图美术总监：主体、构图、光色与材质",
    content: "生成时先锁定画面的用途和第一视觉中心，再按“主体与动作 → 场景关系 → 风格媒介 → 构图景别 → 明确光源 → 主辅色 → 材质细节”组织为自然语言，不堆砌空泛质量词。主体必须一眼可读，轮廓有辨识度，前中后景层次清楚；用具体光位、光质和色温塑造体积与情绪，不使用笼统的‘漂亮光线’。细节只服务主体、剧情和时代，背景不得抢脸，画面保留呼吸空间。提示词保持紧凑，重要要求前置；需要修图或重做时一次只改一个可观察变量。",
    tags: ["生图", "美术指导", "构图", "光影", "材质", "默认启用"],
    source: "开源方法综合 · OpenAI ImageGen 与 Black Forest Labs FLUX Best Practices",
    sourceUrl: "https://github.com/black-forest-labs/skills/tree/master/skills/flux-best-practices",
  },
  {
    id: "image-character-casting-beauty",
    agentId: "image",
    title: "角色选角审美：好看、耐看且不网红同脸",
    content: "用户追求的“好看”默认拆成六项可观察标准：①五官比例协调但不套网红模板；②眼神有焦点、嘴角与面颊松弛有生命力；③脸、发型和服装轮廓一眼可辨；④肤色/材质干净通透且保留角色年龄与经历；⑤主次配色克制、妆发服装符合身份；⑥柔和主光、自然眼神光和清楚的脸部明暗塑造。先从年龄、经历、阶层、性格与戏剧功能确定气质，再设计一个主记忆点与两个辅助特征。禁止尖锥下巴、过度大眼厚唇、蜡像塑料皮、灰脏肤色、僵硬假笑、空洞眼神、随机首饰和批量同脸。不同角色必须在头脸轮廓、眼眉、鼻口、年龄感和气质上明显区分；同一制作任务会话只绑定一张已批准的 Canonical 基准身份图，跨造型只改变服装、妆发和剧情状态。该约束位于业务工作流层，不宣称引擎永久不变。",
    tags: ["生图", "人物审美", "选角", "五官", "反同脸", "默认启用"],
    source: "漫镜原创预设 · 人像生成与角色设计工作流综合",
    sourceUrl: "https://openai.com/academy/image-generation/",
  },
  {
    id: "image-reference-identity-lock",
    agentId: "image",
    title: "参考图分工与人物身份锁定",
    content: "默认角色卡固定为16:9四区布局：左侧35%-40%是严格平视的大正脸大头特写；右侧从上到下为正面全身、45°侧面全身、背面全身，统一轻微T-pose、纯白背景、均匀平光、手脚完整。大头特写相对优先级1.2，用于约束五官脸型；三视图相对优先级1.05，用于约束体型、发型和服装；服务商总引导强度不得超过1.5，若接口不支持权重字段，只把这些值作为提示词职责优先级，禁止发送无效参数。同一任务每个角色只允许一份基准身份来源，不同时传入多份历史脸；每4镜重新挂载同一角色卡以降低长序列漂移。极端俯仰、纯侧后或后3/4镜头仍需补充对应角度用户参考。身份漂移时只重做漂移变量，不堆叠互相冲突的参考图。",
    tags: ["生图", "参考图", "人物一致性", "身份锁定", "默认启用"],
    source: "开源方法综合 · InstantID 与 PhotoMaker",
    sourceUrl: "https://github.com/instantX-research/InstantID",
  },
  {
    id: "image-human-preference-quality-gate",
    agentId: "image",
    title: "生图审美质量闸门：多维评分后再采用",
    content: "采用角色标准卡前独立评分：正脸区域、45°侧面轮廓、背面轮廓、五官身份、头身比与三视图服装一致性；采用普通画面前分别评分提示词符合度、人物脸部与神态、构图焦点、光色材质、解剖技术缺陷以及与当前任务 Canonical 身份和画风的一致性。不得用总分掩盖单项硬伤：区域缺失、不同人物、侧脸畸变、背面发型或服装冲突、肢体截断、人物脸崩、空洞眼神、风格错位任一出现即 REVISE。修订只写可见问题与最小改动；连续失败时更换种子或缩短动作，不继续堆提示词。",
    tags: ["生图", "审美评分", "质量闸门", "人类偏好", "默认启用"],
    source: "开源方法综合 · ImageReward 与 VisionReward 多维人类偏好评估",
    sourceUrl: "https://github.com/zai-org/VisionReward",
  },

  {
    id: "video-model-routing",
    agentId: "video",
    title: "按镜头需求选择视频模型",
    content: "选择模型前识别镜头类型：文生视频、图生视频、首尾帧、人物表演、快速运动、产品展示或风格化镜头。优先使用用户已配置且验证可用的模型，不虚构模型参数。提交前检查模型支持的时长、画幅、分辨率、参考图数量和必填字段。模型失败时保留任务与素材，区分鉴权、参数、队列、生成和下载错误，再决定重试、降级或换模型。",
    tags: ["视频模型", "模型路由", "失败处理", "参数检查"],
    source: "漫镜原创预设 · Pexo 自动路由启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "video-shot-duration",
    agentId: "video",
    title: "15秒以内逐镜生成与长视频组装",
    content: "任何超过模型单次上限的视频都必须先拆成独立镜头，默认单镜控制在3至10秒，绝不把长视频当作一次生成任务。逐镜保存镜头编号、文字 Start/End State、提示词、模型、时长、任务ID和结果文件；首尾抽帧只保存为本地质检证据，不进入下一次生成请求。上一镜通过后自动定位并生成下一条真正缺失的镜头；失败只重跑当前镜头，待审核候选不得重复扣费。全部镜头完成后交给剪辑 Agent 按分镜顺序组装。",
    tags: ["15秒", "逐镜生成", "长视频", "断点续作"],
    source: "漫镜原创预设 · ViMax/Pexo 多镜头启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "video-motion-prompt",
    agentId: "video",
    title: "可控运动提示词",
    content: "运动提示词只描述时间内发生的变化，结构为：主体初始状态、主要动作、动作速度和幅度、镜头运动、环境动态、结束状态、稳定性限制。动作必须符合人物关节、重力和场景空间。避免同时要求多个冲突运镜或过多动作。人物镜头补充面部稳定、手部自然、服装不变；图生视频时不重复改写参考图中已经确定的外观。",
    tags: ["运动提示词", "物理合理", "图生视频", "稳定性"],
    source: "漫镜原创预设 · ViMax 镜头设计启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "video-result-qc",
    agentId: "video",
    title: "视频生成结果验收与最小重试",
    content: "生成后按镜头逐项验收：主体身份、脸和手、服装道具、动作完成度、背景稳定、镜头运动、首尾帧、时长、分辨率和可播放性。只记录可观察问题，不用模糊评价。若失败，先锁定未出错部分，再只修改导致问题的一个或两个变量；连续失败应缩短动作、降低幅度或拆镜。通过的片段立即进入资产库并关联项目和镜头编号。",
    tags: ["视频验收", "重试", "资产库", "质量控制"],
    source: "漫镜原创预设 · ViMax 渲染检查点启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },

  {
    id: "voice-character-profile",
    agentId: "voice",
    title: "角色声线档案与选角",
    content: "为每个角色建立声线档案：年龄感、音高、音色、语速、力度、口音、呼吸感、情绪范围、参考音频和禁止特征。同一角色跨场次优先复用相同音色与参数。选角时先匹配人物身份和表演需求，再考虑音色好听与否。声音克隆只使用用户有权使用的样本，并记录授权来源。",
    tags: ["声线", "选角", "声音一致性", "授权"],
    source: "漫镜原创预设 · SmartSub/ZastTranslate 启发（MIT）",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },
  {
    id: "voice-performance-markup",
    agentId: "voice",
    title: "对白表演标注",
    content: "合成前把台词按意群切分，并标注说话对象、行动目的、潜台词、情绪强度、重音、停顿、速度变化和句尾走向。情绪不等于全句同一种强度，重要变化应落在关键词和停顿上。旁白优先清晰与节奏，对话优先人物关系和即时反应。避免用标点堆砌代替真实表演指令。",
    tags: ["对白", "表演", "重音", "停顿"],
    source: "漫镜原创预设 · 配音工作流综合",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },
  {
    id: "voice-timing-fit",
    agentId: "voice",
    title: "逐句时长匹配与单句重合成",
    content: "按字幕时间段逐句生成并测量真实音频时长。优先通过自然停顿、语速小幅调整和借用静音间隙匹配时间；超限时先精简不影响意思的文字，再考虑变速。不得直接截断台词。问题句单独试听、修改和重合成，不重跑整段。记录每句开始、结束、实际时长、音色和修改原因。",
    tags: ["时长匹配", "逐句", "重合成", "字幕"],
    source: "漫镜预设 · SmartSub/ZastTranslate 方法启发（MIT）",
    sourceUrl: "https://github.com/zast57/ZastTranslate",
  },
  {
    id: "voice-audio-qc",
    agentId: "voice",
    title: "配音质量检查与音轨交付",
    content: "交付前逐句检查错字、漏字、多音字、人名读音、爆音、底噪、音量突变、语速、情绪和时间轴。对白、旁白、环境声和音乐分轨保存。混音时对白优先，音乐遇对白自动压低但不完全消失；必要时保留原环境声。输出音频时附带字幕、角色音色映射和需要人工复核的异常清单。",
    tags: ["配音验收", "混音", "音轨", "异常清单"],
    source: "漫镜预设 · SmartSub 方法启发（MIT）",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },

  {
    id: "editor-assembly",
    agentId: "editor",
    title: "按叙事功能组装镜头",
    content: "先按分镜和场次组装粗剪，不先堆转场和特效。每次剪切必须回答：观众此刻需要看见什么、为什么现在切、切后获得什么新信息。优先保证因果、空间、动作和情绪连续，再调整节奏。反应镜头应放在引发反应的动作之后；信息未读清前不要过早切走；重复表达同一信息的镜头应精简。",
    tags: ["剪辑", "粗剪", "叙事", "节奏"],
    source: "漫镜原创预设 · Pexo 多镜头组装启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  {
    id: "editor-continuity",
    agentId: "editor",
    title: "剪辑连续性与转场选择",
    content: "逐剪检查动作相位、屏幕方向、视线、主体位置、亮度色温、环境声和说话口型。优先使用硬切、动作匹配、视线匹配和声音桥；只有时空、情绪或段落确实变化时才使用明显转场。AI 片段首尾不稳定时先裁掉异常帧，再判断能否通过插入反应、环境或特写镜头修复，不用花哨转场掩盖连续性错误。",
    tags: ["连续性", "转场", "动作匹配", "声音桥"],
    source: "漫镜原创预设 · ViMax 连续性启发（MIT）",
    sourceUrl: "https://github.com/HKUDS/ViMax",
  },
  {
    id: "editor-subtitle",
    agentId: "editor",
    title: "字幕断句、校对与可读性",
    content: "字幕按语义和呼吸断句，不把连接词、姓名或固定词组拆开。逐句核对画面、音频和文字，修正错字、多音字、标点和时间轴。控制每行长度和屏幕停留时间，重要信息避免与画面关键文字重叠。修改字幕后同步检查配音脚本；问题行支持单独恢复、重做和重新合成。",
    tags: ["字幕", "断句", "校对", "可读性"],
    source: "漫镜预设 · SmartSub 方法启发（MIT）",
    sourceUrl: "https://github.com/buxuku/SmartSub",
  },
  {
    id: "editor-mix-export",
    agentId: "editor",
    title: "音频混合与平台导出验收",
    content: "混音顺序为对白清晰、环境连续、音乐服务情绪、音效强调关键动作。对白期间对音乐做平滑 ducking，避免突然抽空；镜头切换处保留连续环境底。导出前检查总时长、画幅、分辨率、帧率、音画同步、黑帧、静音、字幕安全区和文件可播放性。根据平台分别生成9:16、16:9或1:1版本，不用简单裁切破坏主体构图。",
    tags: ["混音", "导出", "画幅", "平台适配"],
    source: "漫镜预设 · Pexo/SmartSub 方法启发（MIT）",
    sourceUrl: "https://github.com/pexoai/pexo-skills",
  },
  ...IMPORTED_DEFAULT_SKILLS,
];
