"use client";

import { useEffect, useMemo, useState } from "react";
import SiteNav from "../components/SiteNav";
import { AGENT_PROFILES, LearnedItem, createLearnedItem, mergeLearnedItems, readLearnedItems, writeLearnedItems } from "../agent-system/learning-store";

type SearchResult = { title?: string; text?: string; url?: string; content?: unknown };
type DouyinToken = { access_token?: string; refresh_token?: string; open_id?: string };
const MCP_KEY = "manjing-mcp-connections-v145";
const BRIDGE_KEY = "manjing-learning-bridge-v145";
const DOUYIN_KEY = "manjing-douyin-account-v145";

function resultText(value: unknown): string {
  if (typeof value === "string") return value;
  if (Array.isArray(value)) return value.map(resultText).filter(Boolean).join("\n");
  if (value && typeof value === "object") { const item = value as Record<string, unknown>; return resultText(item.text || item.content || item.snippet || item.description || JSON.stringify(item)); }
  return "";
}
function inferKind(text: string): "skill" | "memory" { return /数据|趋势|案例|事实|设定|偏好|背景|资料|统计/.test(text) ? "memory" : "skill"; }
function inferTags(text: string) { return ["剧本", "分镜", "人物", "视频", "配音", "剪辑", "提示词", "模型"].filter((tag) => text.includes(tag)); }

export default function LearningPage() {
  const [agentId, setAgentId] = useState("writer");
  const [endpoint, setEndpoint] = useState(""); const [apiKey, setApiKey] = useState(""); const [tool, setTool] = useState("");
  const [tools, setTools] = useState<{ name: string; description?: string }[]>([]); const [query, setQuery] = useState("");
  const [bridgeUrl, setBridgeUrl] = useState("http://127.0.0.1:8765"); const [bridgeToken, setBridgeToken] = useState("");
  const [items, setItems] = useState<LearnedItem[]>([]); const [status, setStatus] = useState("等待创建学习任务"); const [busy, setBusy] = useState(false); const [autoLearn, setAutoLearn] = useState(true);
  const [douyinClientKey, setDouyinClientKey] = useState(""); const [douyinClientSecret, setDouyinClientSecret] = useState(""); const [douyinRedirect, setDouyinRedirect] = useState(""); const [douyinCode, setDouyinCode] = useState(""); const [douyinToken, setDouyinToken] = useState<DouyinToken>({}); const [douyinShare, setDouyinShare] = useState("");

  useEffect(() => { setItems(readLearnedItems()); try {
    const saved = JSON.parse(localStorage.getItem(MCP_KEY) || "{}"); setEndpoint(String(saved.endpoint || "")); setApiKey(String(saved.apiKey || "")); setTool(String(saved.tool || ""));
    const bridge = JSON.parse(localStorage.getItem(BRIDGE_KEY) || "{}"); if (bridge.url) setBridgeUrl(String(bridge.url)); if (bridge.token) setBridgeToken(String(bridge.token)); if (typeof bridge.autoLearn === "boolean") setAutoLearn(bridge.autoLearn);
    const douyin = JSON.parse(localStorage.getItem(DOUYIN_KEY) || "{}"); setDouyinClientKey(String(douyin.clientKey || "")); setDouyinRedirect(String(douyin.redirectUri || "")); setDouyinToken(douyin.token || {});
  } catch {} }, []);

  const candidates = useMemo(() => items.filter((item) => item.status === "candidate"), [items]);
  const selectedAgent = AGENT_PROFILES.find((item) => item.id === agentId) || AGENT_PROFILES[0];
  function persist(next: LearnedItem[]) { const merged = mergeLearnedItems([], next); setItems(merged); writeLearnedItems(merged); }
  function saveConnections() { localStorage.setItem(MCP_KEY, JSON.stringify({ endpoint: endpoint.trim(), apiKey: apiKey.trim(), tool })); localStorage.setItem(BRIDGE_KEY, JSON.stringify({ url: bridgeUrl.trim(), token: bridgeToken.trim(), autoLearn })); }
  function bridgeHeaders(json = false): Record<string, string> { return { ...(json ? { "Content-Type": "application/json" } : {}), ...(bridgeToken.trim() ? { Authorization: `Bearer ${bridgeToken.trim()}` } : {}) }; }
  function persistDouyin(token = douyinToken) { localStorage.setItem(DOUYIN_KEY, JSON.stringify({ clientKey: douyinClientKey.trim(), redirectUri: douyinRedirect.trim(), token })); }
  function learnedItem(input: { title: string; content: string; source: string; sourceUrl?: string; kind?: "skill" | "memory"; confidence?: number }) { const kind = input.kind || inferKind(`${input.title} ${input.content}`); return createLearnedItem({ agentId, kind, title: input.title, content: input.content, source: input.source, sourceUrl: input.sourceUrl || "", confidence: input.confidence || 75, enabled: autoLearn, status: autoLearn ? "approved" : "candidate", memoryClass: kind === "skill" ? "permanent" : "experience", scope: "agent", importance: kind === "skill" ? 8 : 6, tags: inferTags(`${input.title} ${input.content}`), whyRemembered: `由 ${input.source} 提炼，保留来源以便复核` }); }

  async function discover() { if (!endpoint.trim()) return setStatus("请先填写 MCP HTTP 地址"); setBusy(true); setStatus("正在连接 MCP 并发现搜索工具…"); saveConnections(); try { const response = await fetch("/api/desktop/mcp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "tools", endpoint, apiKey }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `连接失败（${response.status}）`); const next = Array.isArray(data.tools) ? data.tools : []; setTools(next); if (!tool && next[0]) setTool(next[0].name); setStatus(`连接成功，发现 ${next.length} 个工具`); } catch (error) { setStatus(error instanceof Error ? error.message : "MCP 连接失败"); } finally { setBusy(false); } }
  async function search() { if (!query.trim()) return setStatus("请输入要学习的主题"); setBusy(true); setStatus(`${selectedAgent.name} 正在通过 MCP 搜索并整理来源…`); saveConnections(); try { const response = await fetch("/api/desktop/mcp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "search", endpoint, apiKey, tool, query }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `搜索失败（${response.status}）`); const raw = Array.isArray(data.results) ? data.results : [data.result || data]; const learned = raw.slice(0, 12).map((entry: SearchResult, index: number) => learnedItem({ title: entry.title || `${query.trim()} · 学习发现 ${index + 1}`, content: resultText(entry).slice(0, 5000) || "该来源没有返回可读文本", source: "MCP 搜索", sourceUrl: entry.url, confidence: 72 })); persist([...items, ...learned]); setStatus(autoLearn ? `${selectedAgent.name} 已自动学习并启用 ${learned.length} 条知识` : `已生成 ${learned.length} 条候选知识`); } catch (error) { setStatus(error instanceof Error ? error.message : "MCP 搜索失败"); } finally { setBusy(false); } }
  async function recognize(file?: File) { if (!file) return; setBusy(true); setStatus("本地桥接正在提取音频、识别语音和画面字幕…"); saveConnections(); try { const form = new FormData(); form.append("video", file); form.append("language", "zh"); const response = await fetch(`${bridgeUrl.replace(/\/$/, "")}/v1/learn/video`, { method: "POST", headers: bridgeHeaders(), body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || `识别失败（${response.status}）`); const next = learnedItem({ title: `${file.name} · 视频学习记忆`, content: `【语音转写】\n${String(data.transcript || "未识别到语音")}\n\n【画面字幕】\n${Array.isArray(data.ocr) ? data.ocr.join("\n") : String(data.ocr || "未识别到画面文字")}`.slice(0, 12000), source: "本地视频识别", kind: "memory", confidence: 80 }); persist([...items, next]); setStatus(autoLearn ? `${selectedAgent.name} 已自动写入并启用视频记忆` : "识别完成，等待审核"); } catch (error) { setStatus(error instanceof Error ? error.message : "本地识别失败"); } finally { setBusy(false); } }

  function openDouyinAuth() { if (!douyinClientKey.trim() || !douyinRedirect.trim()) return setStatus("请填写 Client Key 和已登记的 HTTPS 回调地址"); const target = new URL("https://open.douyin.com/platform/oauth/connect/"); target.searchParams.set("client_key", douyinClientKey.trim()); target.searchParams.set("response_type", "code"); target.searchParams.set("scope", "user_info,video.list.bind,video.data"); target.searchParams.set("redirect_uri", douyinRedirect.trim()); target.searchParams.set("state", crypto.randomUUID()); persistDouyin(); window.open(target.toString(), "_blank", "noopener,noreferrer"); setStatus("已打开抖音官方授权页，授权后把回调地址里的 code 粘贴回来"); }
  async function exchangeDouyinCode() { setBusy(true); setStatus("正在交换抖音授权令牌…"); try { const response = await fetch(`${bridgeUrl.replace(/\/$/, "")}/v1/douyin/oauth/exchange`, { method: "POST", headers: bridgeHeaders(true), body: JSON.stringify({ client_key: douyinClientKey, client_secret: douyinClientSecret, code: douyinCode }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "抖音授权失败"); const token = { access_token: data.access_token, refresh_token: data.refresh_token, open_id: data.open_id }; setDouyinToken(token); persistDouyin(token); setDouyinClientSecret(""); setDouyinCode(""); setStatus("抖音账号连接成功，令牌仅保存在当前电脑"); } catch (error) { setStatus(error instanceof Error ? error.message : "抖音授权失败"); } finally { setBusy(false); } }
  async function syncDouyinAccount() { if (!douyinToken.access_token || !douyinToken.open_id) return setStatus("请先连接抖音账号"); setBusy(true); setStatus(`${selectedAgent.name} 正在读取你授权的本人作品…`); try { const response = await fetch(`${bridgeUrl.replace(/\/$/, "")}/v1/douyin/account`, { method: "POST", headers: bridgeHeaders(true), body: JSON.stringify(douyinToken) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "读取账号失败"); const profile = data.profile || {}; const videos = Array.isArray(data.videos?.list) ? data.videos.list : []; const learned = videos.slice(0, 30).map((video: Record<string, unknown>, index: number) => learnedItem({ title: String(video.title || video.item_title || `本人抖音作品 ${index + 1}`), content: `用户本人抖音作品资料：${resultText(video)}`.slice(0, 5000), source: `抖音账号 · ${String(profile.nickname || "已授权用户")}`, sourceUrl: String(video.share_url || video.shareUrl || ""), kind: "memory", confidence: 95 })); persist([...items, ...learned]); setStatus(`已同步 ${learned.length} 条本人作品${autoLearn ? "并自动写入记忆" : "，等待审核"}`); } catch (error) { setStatus(error instanceof Error ? error.message : "同步失败，请检查 video.list 权限"); } finally { setBusy(false); } }
  async function learnDouyinShare() { if (!douyinShare.trim()) return setStatus("请粘贴你有权处理的抖音分享内容"); setBusy(true); setStatus("正在本地下载并进行语音、字幕识别…"); try { const response = await fetch(`${bridgeUrl.replace(/\/$/, "")}/v1/douyin/share/learn`, { method: "POST", headers: bridgeHeaders(true), body: JSON.stringify({ share_text: douyinShare, language: "zh" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "抖音视频学习失败"); const next = learnedItem({ title: `${String(data.title || "抖音视频")} · 学习笔记`, content: `【视频标题】${String(data.title || "")}\n\n【语音转写】\n${String(data.transcript || "未识别到语音")}\n\n【画面字幕】\n${Array.isArray(data.ocr) ? data.ocr.join("\n") : String(data.ocr || "未识别到字幕")}`.slice(0, 15000), source: "用户提交的抖音分享链接", sourceUrl: String(data.source_url || ""), confidence: 82 }); persist([...items, next]); setDouyinShare(""); setStatus(autoLearn ? `${selectedAgent.name} 已自动学习该视频` : "识别完成，等待审核"); } catch (error) { setStatus(error instanceof Error ? error.message : "抖音分享链接学习失败"); } finally { setBusy(false); } }
  function patch(id: string, changes: Partial<LearnedItem>) { persist(items.map((item) => item.id === id ? { ...item, ...changes } : item)); } function remove(id: string) { persist(items.filter((item) => item.id !== id)); }

  return <main className="learning-page"><SiteNav current="learning" /><section className="learning-hero"><div><span>AGENT LEARNING LAB</span><h1>让 Agent 主动搜索，也学得有据可查。</h1><p>MCP 寻找资料，本地识别听懂视频。自动学习会分类写入岗位技能或长期记忆，并保留来源和撤销能力。</p></div><aside className="auto-learn-switch"><label><input type="checkbox" checked={autoLearn} onChange={(event) => { setAutoLearn(event.target.checked); localStorage.setItem(BRIDGE_KEY, JSON.stringify({ url: bridgeUrl.trim(), token: bridgeToken.trim(), autoLearn: event.target.checked })); }} /><i /><span><b>自动学习</b><small>{autoLearn ? "搜索后立即分类入库" : "搜索后等待人工审核"}</small></span></label></aside></section>
    <section className="learning-shell"><aside className="learning-agents"><b>学习岗位</b>{AGENT_PROFILES.map((agent) => <button key={agent.id} className={agent.id === agentId ? "active" : ""} onClick={() => setAgentId(agent.id)}><i>{agent.icon}</i><span><strong>{agent.name}</strong><small>{agent.duty}</small></span></button>)}</aside><section className="learning-workbench">
      <header><div><span>01 · MCP SEARCH</span><h2>搜索与采集</h2></div><em>{status}</em></header><div className="learning-config-grid"><label>MCP HTTP 地址<input value={endpoint} onChange={(event) => setEndpoint(event.target.value)} placeholder="https://example.com/mcp" /></label><label>访问密钥（可选）<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="Bearer Token" /></label><button disabled={busy} onClick={discover}>发现工具</button></div><div className="learning-search-row"><select value={tool} onChange={(event) => setTool(event.target.value)}><option value="">自动选择搜索工具</option>{tools.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</select><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索需要学习的创作方法" /><button disabled={busy} onClick={search}>交给 {selectedAgent.name}</button></div>
      <section className="douyin-learning"><header><div><span>02 · DOUYIN CONNECT</span><h2>连接自己的抖音</h2><p>官方 OAuth 用于本人账号；分享链接入口只处理用户主动提交且有权学习的内容。</p></div><em>{douyinToken.access_token ? "账号已连接" : "等待授权"}</em></header><div className="douyin-oauth-grid"><input value={douyinClientKey} onChange={(event) => setDouyinClientKey(event.target.value)} placeholder="抖音开放平台 Client Key" /><input type="password" value={douyinClientSecret} onChange={(event) => setDouyinClientSecret(event.target.value)} placeholder="Client Secret（不保存）" /><input value={douyinRedirect} onChange={(event) => setDouyinRedirect(event.target.value)} placeholder="已登记的 HTTPS 回调地址" /><button onClick={openDouyinAuth}>打开官方授权</button><input value={douyinCode} onChange={(event) => setDouyinCode(event.target.value)} placeholder="粘贴授权回调中的 code" /><button disabled={busy} onClick={exchangeDouyinCode}>完成账号连接</button><button disabled={busy || !douyinToken.access_token} onClick={syncDouyinAccount}>同步本人作品并学习</button></div><div className="douyin-share-row"><input value={douyinShare} onChange={(event) => setDouyinShare(event.target.value)} placeholder="粘贴你有权处理的抖音分享链接或分享文本" /><button disabled={busy} onClick={learnDouyinShare}>本地识别并学习</button></div><small>官方账号功能需要应用审核通过 user_info、video.list.bind/video.data 权限；令牌保存在本机，Client Secret 不保存。</small></section>
      <div className="local-recognition"><div><span>03 · LOCAL VISION & SPEECH</span><h2>本地视频识别</h2><p>使用 FFmpeg、Faster Whisper 和 PaddleOCR，素材不上传第三方识别平台。</p></div><div><input value={bridgeUrl} onChange={(event) => setBridgeUrl(event.target.value)} aria-label="本地桥接地址" /><input type="password" value={bridgeToken} onChange={(event) => setBridgeToken(event.target.value)} placeholder="桥接密钥（可选）" /><label><input type="file" accept="video/*" onChange={(event) => { void recognize(event.target.files?.[0]); event.currentTarget.value = ""; }} />选择视频并识别</label></div></div>
      <section className="candidate-board"><header><div><span>04 · REVIEW</span><h2>候选知识审核</h2></div><small>关闭自动学习时在这里确认</small></header>{!candidates.length ? <div className="candidate-empty">当前没有待审核内容。自动学习的结果可以在“技能与记忆”中管理。</div> : candidates.map((item) => <article key={item.id}><div><input value={item.title} onChange={(event) => patch(item.id, { title: event.target.value })} /><span>{item.source} · 置信度 {item.confidence}%</span></div><textarea value={item.content} onChange={(event) => patch(item.id, { content: event.target.value })} /><footer><select value={item.kind} onChange={(event) => patch(item.id, { kind: event.target.value as "skill" | "memory" })}><option value="skill">保存为技能</option><option value="memory">保存为长期记忆</option></select><button className="ghost" onClick={() => remove(item.id)}>删除</button><button onClick={() => patch(item.id, { status: "approved", enabled: true })}>确认并同步</button></footer></article>)}</section>
    </section></section>
  </main>;
}
