"use client";
import { useEffect, useState } from "react";
import { listLibraryAssets, updateLibraryAsset, type LibraryAsset } from "../lib/asset-library";

export default function EnterpriseAssetPanel(){
 const [mode,setMode]=useState("personal"),[assets,setAssets]=useState<LibraryAsset[]>([]),[assetId,setAssetId]=useState(""),[ak,setAk]=useState(""),[sk,setSk]=useState(""),[groupId,setGroupId]=useState(""),[url,setUrl]=useState(""),[status,setStatus]=useState("AI 写实虚拟人像可提交到企业私域素材库。"),[busy,setBusy]=useState(false);
 useEffect(()=>{void listLibraryAssets().then(x=>setAssets(x.filter(a=>a.category==="character"&&a.mediaType==="image")));try{const s=JSON.parse(localStorage.getItem("manjing-enterprise-assets-v1")||"null");if(s){setMode(s.mode||"personal");setAk(s.ak||"");setGroupId(s.groupId||"")}}catch{}},[]);
 const enabled=mode==="advanced"||mode==="premium";
 async function submit(){const asset=assets.find(a=>a.id===assetId);if(!enabled){setStatus("企业基础权益不支持 Assets API，请开通高级或 Premium 权益。");return}if(!asset||!ak||!sk||!groupId||!url){setStatus("请选择人物并填写 AK、SK、Asset Group ID 和 HTTPS 图片地址。");return}setBusy(true);try{localStorage.setItem("manjing-enterprise-assets-v1",JSON.stringify({mode,ak,groupId}));const r=await fetch("/api/desktop/enterprise-assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",accessKeyId:ak,secretKey:sk,groupId,name:asset.name,url,assetType:"image",projectName:"default"})});const d=await r.json();if(!r.ok||!d.id)throw new Error(d.error||"方舟未返回 Asset ID");await updateLibraryAsset(asset.id,{arkAssetId:d.id,portraitAuthorizationStatus:"pending"});setSk("");setStatus(`提交成功：${d.id}。审核通过后将自动按 asset://${d.id} 引用。`)}catch(e){setStatus(e instanceof Error?e.message:"提交失败")}finally{setBusy(false)}}
 const box={border:"1px solid #d8cec0",borderRadius:22,padding:24,margin:"0 clamp(18px,4vw,64px) 26px",background:"linear-gradient(135deg,#fffdf9,#f3eee6)"} as const,input={padding:11,border:"1px solid #d8cec0",borderRadius:10,background:"white"} as const;
 return <section style={box}><p style={{color:"#b75e37",fontWeight:800,letterSpacing:".15em"}}>VOLCENGINE ENTERPRISE ASSETS</p><h2 style={{fontSize:30,margin:"8px 0 18px"}}>企业虚拟人像入库中心</h2><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:18}}>{[["personal","个人"],["basic","企业基础"],["advanced","企业高级"],["premium","企业 Premium"]].map(x=><button key={x[0]} onClick={()=>setMode(x[0])} style={{padding:"9px 14px",borderRadius:20,border:"1px solid #cbbfb2",background:mode===x[0]?"#c66c42":"white",color:mode===x[0]?"white":"#332a27"}}>{x[1]}</button>)}</div>{enabled?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}><select style={input} value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">选择漫镜人物资产</option>{assets.map(a=><option key={a.id} value={a.id}>{a.identityKey||a.name}</option>)}</select><input style={input} value={groupId} onChange={e=>setGroupId(e.target.value)} placeholder="Asset Group ID"/><input style={input} value={ak} onChange={e=>setAk(e.target.value)} placeholder="Access Key ID"/><input style={input} type="password" value={sk} onChange={e=>setSk(e.target.value)} placeholder="Secret Key（不保存）"/><input style={{...input,gridColumn:"1/-1"}} value={url} onChange={e=>setUrl(e.target.value)} placeholder="公网 HTTPS/TOS 图片 URL"/><button disabled={busy} onClick={()=>void submit()} style={{padding:12,border:0,borderRadius:10,background:"#262126",color:"white"}}>{busy?"正在提交":"一键提交企业虚拟人像"}</button></div>:<p>当前模式使用公共虚拟人像或控制台流程；企业高级/Premium 可使用 Assets API。</p>}<p style={{padding:12,background:"white",borderRadius:10}}>{status}</p></section>
}
